### ISSUE TITLE
Error selecting seed value

### ISSUE THREAD

**Issue by Suzanne0** [GMouYes/BiQQLSTM_HS#1]
When I run the Biqqlstm.py, I got this error
  seed = int(sys.argv[1])

IndexError: list index out of range

Can you please help me?
Thanks in advance

**Comment by GMouYes** [comment]
Hi Suzanne0,
It seems you did not feed your chosen seed in the input command. If you check our readme file in /code folder, there is detailed instruction for running the code with an example where seed=1. Hopefully my reply is helpful.

> When I run the Biqqlstm.py, I got this error seed = int(sys.argv[1])
> 
> IndexError: list index out of range
> 
> Can you please help me? Thanks in advance

**Comment by Suzanne0** [comment]
> Hi Suzanne0, It seems you did not feed your chosen seed in the input command. If you check our readme file in /code folder, there is detailed instruction for running the code with an example where seed=1. Hopefully my reply is helpful.
> 
> > When I run the Biqqlstm.py, I got this error seed = int(sys.argv[1])
> > IndexError: list index out of range
> > Can you please help me? Thanks in advance

I got it, Thanks a lot
